spring:
  application:
    name: spring-boot-batch-processing
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver


  h2:
    console:
      enabled: true

  #      batch configuration

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS

  jpa:
    hibernate:
      ddl-auto: create-drop

  output:
    ansi:
      enabled: ALWAYS



